// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: polling.proto

package polling

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PollingService_UpdateConfig_FullMethodName = "/polling.PollingService/UpdateConfig"
	PollingService_StreamData_FullMethodName   = "/polling.PollingService/StreamData"
)

// PollingServiceClient is the client API for PollingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PollingServiceClient interface {
	UpdateConfig(ctx context.Context, in *ConfigPayload, opts ...grpc.CallOption) (*StatusResponse, error)
	StreamData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PollingService_StreamDataClient, error)
}

type pollingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPollingServiceClient(cc grpc.ClientConnInterface) PollingServiceClient {
	return &pollingServiceClient{cc}
}

func (c *pollingServiceClient) UpdateConfig(ctx context.Context, in *ConfigPayload, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PollingService_UpdateConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollingServiceClient) StreamData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PollingService_StreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &PollingService_ServiceDesc.Streams[0], PollingService_StreamData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pollingServiceStreamDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PollingService_StreamDataClient interface {
	Recv() (*DataPayload, error)
	grpc.ClientStream
}

type pollingServiceStreamDataClient struct {
	grpc.ClientStream
}

func (x *pollingServiceStreamDataClient) Recv() (*DataPayload, error) {
	m := new(DataPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PollingServiceServer is the server API for PollingService service.
// All implementations must embed UnimplementedPollingServiceServer
// for forward compatibility
type PollingServiceServer interface {
	UpdateConfig(context.Context, *ConfigPayload) (*StatusResponse, error)
	StreamData(*Empty, PollingService_StreamDataServer) error
	mustEmbedUnimplementedPollingServiceServer()
}

// UnimplementedPollingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPollingServiceServer struct {
}

func (UnimplementedPollingServiceServer) UpdateConfig(context.Context, *ConfigPayload) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedPollingServiceServer) StreamData(*Empty, PollingService_StreamDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamData not implemented")
}
func (UnimplementedPollingServiceServer) mustEmbedUnimplementedPollingServiceServer() {}

// UnsafePollingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PollingServiceServer will
// result in compilation errors.
type UnsafePollingServiceServer interface {
	mustEmbedUnimplementedPollingServiceServer()
}

func RegisterPollingServiceServer(s grpc.ServiceRegistrar, srv PollingServiceServer) {
	s.RegisterService(&PollingService_ServiceDesc, srv)
}

func _PollingService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollingServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollingService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollingServiceServer).UpdateConfig(ctx, req.(*ConfigPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollingService_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PollingServiceServer).StreamData(m, &pollingServiceStreamDataServer{stream})
}

type PollingService_StreamDataServer interface {
	Send(*DataPayload) error
	grpc.ServerStream
}

type pollingServiceStreamDataServer struct {
	grpc.ServerStream
}

func (x *pollingServiceStreamDataServer) Send(m *DataPayload) error {
	return x.ServerStream.SendMsg(m)
}

// PollingService_ServiceDesc is the grpc.ServiceDesc for PollingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PollingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "polling.PollingService",
	HandlerType: (*PollingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConfig",
			Handler:    _PollingService_UpdateConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _PollingService_StreamData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "polling.proto",
}
