# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polling_pb2 as polling__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PollingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateConfig = channel.unary_unary(
                '/polling.PollingService/UpdateConfig',
                request_serializer=polling__pb2.ConfigPayload.SerializeToString,
                response_deserializer=polling__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StreamData = channel.unary_stream(
                '/polling.PollingService/StreamData',
                request_serializer=polling__pb2.Empty.SerializeToString,
                response_deserializer=polling__pb2.DataPayload.FromString,
                _registered_method=True)


class PollingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PollingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=polling__pb2.ConfigPayload.FromString,
                    response_serializer=polling__pb2.StatusResponse.SerializeToString,
            ),
            'StreamData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=polling__pb2.Empty.FromString,
                    response_serializer=polling__pb2.DataPayload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polling.PollingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polling.PollingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PollingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polling.PollingService/UpdateConfig',
            polling__pb2.ConfigPayload.SerializeToString,
            polling__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polling.PollingService/StreamData',
            polling__pb2.Empty.SerializeToString,
            polling__pb2.DataPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
