# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: polling.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'polling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpolling.proto\x12\x07polling\"$\n\rConfigPayload\x12\x13\n\x0bjson_config\x18\x01 \x01(\t\" \n\x0b\x44\x61taPayload\x12\x11\n\tjson_data\x18\x01 \x01(\t\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x87\x01\n\x0ePollingService\x12?\n\x0cUpdateConfig\x12\x16.polling.ConfigPayload\x1a\x17.polling.StatusResponse\x12\x34\n\nStreamData\x12\x0e.polling.Empty\x1a\x14.polling.DataPayload0\x01\x42\x0bZ\t./pollingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./polling'
  _globals['_CONFIGPAYLOAD']._serialized_start=26
  _globals['_CONFIGPAYLOAD']._serialized_end=62
  _globals['_DATAPAYLOAD']._serialized_start=64
  _globals['_DATAPAYLOAD']._serialized_end=96
  _globals['_STATUSRESPONSE']._serialized_start=98
  _globals['_STATUSRESPONSE']._serialized_end=148
  _globals['_EMPTY']._serialized_start=150
  _globals['_EMPTY']._serialized_end=157
  _globals['_POLLINGSERVICE']._serialized_start=160
  _globals['_POLLINGSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
